apiVersion: iam.kubesphere.io/v1beta1
kind: RoleTemplate
metadata:
  annotations:
    iam.kubesphere.io/dependencies: '["namespace-view-members"]'
    iam.kubesphere.io/role-template-rules: '{"roles": "view"}'
    meta.helm.sh/release-name: ks-core
    meta.helm.sh/release-namespace: kubesphere-system
  creationTimestamp: "2025-10-16T00:42:02Z"
  generation: 1
  labels:
    app.kubernetes.io/managed-by: Helm
    iam.kubesphere.io/aggregate-to-operator: ""
    iam.kubesphere.io/aggregate-to-viewer: ""
    iam.kubesphere.io/category: namespace-access-control
    iam.kubesphere.io/scope: namespace
    kubesphere.io/managed: "true"
  name: print-ones-workload-viewer
spec:
  description:
    en: View project roles.
    zh: 查看项目角色。
  displayName:
    en: Role Viewing
    zh: 角色查看
  rules:
  - apiGroups:
    - '*'
    resources: ["deployments"]
    resourceNames: ["print-ones"]
    verbs:
    - get
    - list
    - watch
