// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

// TableNameUser defines the physical table name for the UserM model.
const TableNameUser = "{{.Web.BinaryName | extractProjectPrefix}}_user"

// UserM represents the data model for the user resource.
// It maps to the "{{.Web.BinaryName | extractProjectPrefix}}_user" table in the database.
type UserM struct {
	// ID is the primary key of the record.
	ID int64 `gorm:"column:id;primaryKey;autoIncrement:true" json:"id"`

    // UserID is the unique identifier for the resource.
    UserID string `gorm:"column:user_id;not null;uniqueIndex:idx_user_user_id;comment:Unique user ID" json:"user_id"`

    // Username is the unique username for the user.
    Username string `gorm:"column:username;not null;uniqueIndex:idx_user_username;comment:Username (unique)" json:"username"`

    // Password is the hashed password for the user.
    Password string `gorm:"column:password;not null;comment:User password (hashed)" json:"password"`

    // Nickname is the user's nickname.
    Nickname string `gorm:"column:nickname;not null;comment:User nickname" json:"nickname"`

    // Email is the user's email address.
    Email string `gorm:"column:email;not null;comment:User email address" json:"email"`

    // Phone is the user's phone number.
    Phone string `gorm:"column:phone;not null;uniqueIndex:idx_user_phone;comment:User phone number" json:"phone"`

    // CreatedAt is the timestamp when the resource was created.
    CreatedAt time.Time `gorm:"column:created_at;not null;default:current_timestamp;comment:User creation time" json:"created_at"`

    // UpdatedAt is the timestamp when the resource was last modified.
    UpdatedAt time.Time `gorm:"column:updated_at;not null;default:current_timestamp;comment:User last modification time" json:"updated_at"`
}

// TableName returns the physical table name for the UserM model.
func (*UserM) TableName() string {
	return TableNameUser
}
